# Generated by Django 4.1.1 on 2022-09-15 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('recordTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
